spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/etiya-pair2/microservices-configuration
          default-label: main

server:
  port: 8001
